apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  postgres_user: indexer_user
  postgres_password: indexer
  postgres_db: blockchain_indexer
  database_url: postgresql://indexer_user:indexer@postgres:5432/blockchain_indexer